# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    http_method_override: true
    handle_all_throwables: true

    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-host', 'x-forwarded-port', 'x-forwarded-prefix']

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    uid:
        default_uuid_version: 7
        time_based_uuid_version: 7

    http_client:
        scoped_clients:
            # only requests matching scope will use these options
            steamApi.client:
                base_uri: https://api.steampowered.com
                query:
                    key: '%steam_web_api_key%'
                    format: 'json'
